[tool.poetry]
name = "phonocast"
version = "0.1.0"
description = ""
authors = ["Thomas Crha <thomas@9bitbyte.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.97.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
